services:
  mariadb:
    container_name: mariadb
    build:
      context: ./mariadb
      dockerfile: Dockerfile
    image: mariadb
    secrets:
      - db_root_password
      - db_password

  # wordpress:
  #   container_name: wordpress
      # depends_on:
      # - mariadb

  nginx:
    container_name: nginx
    build: ./nginx
    image: nginx
    # depends_on:
    #   - wordpress

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_editor_password:
    file: ../secrets/wp_editor_password.txt
